name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Package Spring Boot App
        run: |
          ./mvnw clean package -DskipTests=true
        working-directory: ./path_to_your_spring_boot_project

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./path_to_your_dockerfile
          push: true
          tags: your_docker_hub_username/your_image_name:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
